Rework extract and integrate into vifm

diff --git a/bin/extract b/bin/extract
--- a/bin/extract
+++ b/bin/extract
@@ -1,20 +1,37 @@
-#!/bin/sh
-if [ -f "$1" ] ; then
-    case "$1" in
-        *.tar.bz2)   tar xvjf "$1"    ;;
-        *.tar.gz)    tar xvzf "$1"    ;;
-        *.tar.xz)    tar xvf "$1"     ;;
-        *.bz2)       bunzip2 "$1"     ;;
-        *.rar)       unrar x "$1"     ;;
-        *.gz)        gunzip "$1"      ;;
-        *.tar)       tar xvf "$1"     ;;
-        *.tbz2)      tar xvjf "$1"    ;;
-        *.tgz)       tar xvzf "$1"    ;;
-        *.zip)       unzip "$1"       ;;
-        *.Z)         uncompress "$1"  ;;
-        *.7z)        7z x "$1"        ;;
-        *)           echo "Cannot extract '$1': Unrecognized file extension" ;;
+#!/usr/bin/env bash
+
+set -e
+
+FILE=$1
+FILE_ABSOLUTE_PATH="$(pwd)/$FILE"
+
+extract() {
+  EXTENSION=$1
+  COMMAND="${@:2}"
+  DIR="$(dirname "$FILE")/$(basename -s ".$EXTENSION" "$FILE")"
+
+  echo "Extracting $FILE into $DIR"
+  mkdir "$DIR"
+  cd "$DIR"
+  echo "$FILE_ABSOLUTE_PATH" | xargs -I%f $COMMAND
+}
+
+if [ -f "$FILE" ] ; then
+    case "$FILE" in
+        *.tar.bz2) extract 'tar.bz2' tar xvjf '%f'   ;;
+        *.tar.gz)  extract 'tar.gz'  tar xvzf '%f'   ;;
+        *.tar.xz)  extract 'tar.xz'  tar xvf '%f'    ;;
+        *.bz2)     extract 'bz2'     bunzip2 '%f'    ;;
+        *.rar)     extract "rar"     unrar x '%f'    ;;
+        *.gz)      extract 'gz'      gunzip '%f'     ;;
+        *.tar)     extract 'tar'     tar xvf '%f'    ;;
+        *.tbz2)    extract 'tbz2'    tar xvjf '%f'   ;;
+        *.tgz)     extract 'tgz'     tar xvzf '%f'   ;;
+        *.zip)     extract 'zip'     unzip '%f'      ;;
+        *.Z)       extract 'Z'       uncompress '%f' ;;
+        *.7z)      extract '7z'      7z x '%f'       ;;
+        *)         echo "Cannot extract '$FILE': Unrecognized file extension" ;;
     esac
 else
-    echo "Cannot extract '$1': File is unreadable"
+    echo "Cannot extract '$FILE': File is unreadable"
 fi
