Update install

diff --git a/install b/install
--- a/install
+++ b/install
@@ -2,29 +2,30 @@
 # If you already have them cloned in ~/.config then just run ~/.config/init.sh to install them
 #
 # curl https://raw.githubusercontent.com/alexdavid/dotfiles/master/install | bash
-
-echo
-echo "Testing if you have access to clone GitHub projects over SSH..."
-if (ssh git@github.com 2>&1 | grep "You've successfully authenticated, but GitHub does not provide shell access"); then
-  echo "Success! Proceding over SSH"
-  ORIGIN="git@github.com:alexdavid/dotfiles.git"
-else
-  echo "Failed! Proceding over HTTP"
-  ORIGIN="https://github.com/alexdavid/dotfiles.git"
-fi
-
-echo
-echo "Checking for existence of ~/.config directory"
-if [ -e ~/.config ]; then
-  echo "~/.config already exists! (Re)move it before running this script"
+(
   echo
-  exit 1
-fi
-
-echo
-echo "Cloning dotfiles"
-git clone $ORIGIN ~/.config
-
-echo
-echo "Initializing"
-~/.config/init.sh
+  echo "Testing if you have access to clone GitHub projects over SSH..."
+  if (ssh git@github.com 2>&1 | grep "You've successfully authenticated, but GitHub does not provide shell access"); then
+    echo "Success! Proceding over SSH"
+    ORIGIN="git@github.com:alexdavid/dotfiles.git"
+  else
+    echo "Failed! Proceding over HTTP"
+    ORIGIN="https://github.com/alexdavid/dotfiles.git"
+  fi
+  
+  echo
+  echo "Checking for existence of ~/.config directory"
+  if [ -e ~/.config ]; then
+    echo "~/.config already exists! (Re)move it before running this script"
+    echo
+    exit 1
+  fi
+  
+  echo
+  echo "Cloning dotfiles"
+  git clone $ORIGIN ~/.config
+  
+  echo
+  echo "Initializing"
+  ~/.config/init.sh
+)
